version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  gateway:
    build: gateway
    image: shareit_gateway
    container_name: shareit_gateway
    ports:
      - "8081:8081"
    depends_on:
      -server
    environment:
      - SHAREIT_SERVER_URL=http://server:8082

  server:
    build: server
    image: shareit_server
    container_name: shareit_server
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root